version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Ronaldo@23
      MYSQL_DATABASE: wissdb
    volumes:
      - ../db:/var/lib/mysql
    ports:
        - "3306:3306"

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    image: notification-service:prod
    container_name: notification-service
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - "8081:8081"
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      - db
      - eureka-server
    ports:
      - "9898:9898"
    restart: on-failure


  gateway:
    image: gateway:latest
    container_name: gateway
    depends_on:
      - notification-service
    ports:
      - "8080:8080"
