version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - "3306:3306"

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  notification-service:
    image: notification-service:prod
    container_name: notification-service
    depends_on:
      - config-server
      - eureka-server
    ports:
      - "8081:8081"
    restart: on-failure
  produit-service:
    image: produit-service:latest
    container_name: produit-service
    depends_on:
      - db
      - eureka-server
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
    ports:
      - "8082:8082"
    restart: on-failure
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "9898:9898"
    depends_on:
      - db
      - eureka-server
    restart: on-failure

  fournisseur-service:
    image: fournisseur-service:latest
    container_name: fournisseur-service
    depends_on:
      - db
      - eureka-server
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/"
    ports:
      - "8084:8084"
    restart: on-failure

  gateway:
    image: gateway:latest
    container_name: gateway
    depends_on:
      - notification-service
      - auth-service
      - produit-service
    ports:
      - "8080:8080"
    restart: on-failure
