version: "3.9"

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: on-failure
    volumes:
      - ../data:/var/lib/mongodb
    ports:
      - "27017:27017"

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - "3306:3306"

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
      
  
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    

  payment:
    image: payment
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - eureka-server



  # notification-service:
  #   image: notification-service:prod
  #   container_name: notification-service
  #   depends_on:
  #     - config-server
  #     - eureka-server
  #   ports:
  #     - "8081:8081"
  #   restart: on-failure

  # auth-service:
  #   image: auth-service:latest
  #   container_name: auth-service
  #   ports:
  #     - "9898:9898"
  #   depends_on:
  #     - db
  #     - eureka-server
  #   restart: on-failure



  # gateway:
  #   image: gateway:latest
  #   container_name: gateway
  #   depends_on:
  #     - notification-service
  #     - auth-service
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure
